### PR TITLE
Home page improvements and news system

### PR DESCRIPTION
**Pull request by ghost**
This PR adds a board table and news items to the white space on the home page. It also adds the aforementioned news system in the database and a page for admins to author news. See screenshots for changes.
Merging this will squash your commit that made all those links into actual links, but my PR does that as well so no work is lost.

### CODE REVIEW

**Comment by knotteye** [comment]
Merge conflicts resolved, should be ready to merge.

**Comment by knotteye** [comment]
Oh I suppose I'll mention issue #15 as this is my solution to that.

**Comment by FChannel0** [comment]
This is good, nice contribution. Is there a way to delete old news as the admin? Can there be a limited number of recent news on the front page, say the latest 3 entries and then a user can view all the entries from the dedicated news page?

Also side note, ill be moving the current instance index from the homepage to a new location so its not cluttered with these changes.

Nice work.

**Comment by knotteye** [comment]
Thanks.

> Is there a way to delete old news as the admin? Can there be a limited number of recent news on the front page, say the latest 3 entries and then a user can view all the entries from the dedicated news page?

Not at the moment but that shouldn't be too hard. I can update this with those changes later today so that you can merge it and move the instance index soon.

**Comment by knotteye** [comment]
@FChannel0 okay, ready for merge. There is a dedicated news page, a delete button for the admin, and the most recent 3 entries show on the home page with the most recent 1 expanded.
demo

**Comment by knotteye** [comment]
@FChannel0 ready to merge with development

**Pull request merged**
